sbin: update cpmulti wrapper
`cp -t` allows copying multiple files to same destination directory,
eliminating need for a shell loop, hence reducing total number of
process invocations.

diff --git a/sbin/cpmulti b/sbin/cpmulti
--- a/sbin/cpmulti
+++ b/sbin/cpmulti
@@ -16,14 +16,17 @@ function usage {
 }
 
 function cpmulti {
-	for f in "${@:2}"; do
-		cp "${1}" "${f}"
-	done
+	cp -t "${1}" "${@:2}"
 }
+
+if [ -z "$(command -v cp)" ]; then
+	echo "Comand not found: cp"
+	exit 255
+fi
 
 if [ "${#}" -lt 2 ]; then
 	usage "${0}"
-	exit 255
+	exit 254
 fi
 
 cpmulti "$@"
