sbin/ffmpeg_avc_to_hevc: allow user to limit working directories

diff --git a/sbin/ffmpeg_avc_to_hevc b/sbin/ffmpeg_avc_to_hevc
--- a/sbin/ffmpeg_avc_to_hevc
+++ b/sbin/ffmpeg_avc_to_hevc
@@ -141,29 +141,41 @@ then
 	HEVC_QUALITY="${DEFAULT_HEVC_QUALITY}"
 fi
 
+if [[ "${#}" == 0 ]]
+then
+	DIRS=( '.' )
+else
+	DIRS=( "${@}" )
+fi
+
+shopt -s nullglob
 shopt -s globstar
-for f in **/*.{mp4,mkv}
+for d in "${DIRS[@]}"
 do
-	if ! [[ -f "${f}" ]]
-	then
-		echo "'${f}' is no a valid file, skipping"...
-		continue
-	fi
+	for f in "${d}"/**/*.{mkv,mp4}
+	do
+		if ! [[ -f "${f}" ]]
+		then
+			echo "'${f}' is no a valid file, skipping"...
+			continue
+		fi
 
-	## shellcheck nags about "get_video_codec "${f}""'s exit code
-	# shellcheck disable=SC2312
-	if [[ "$(get_video_codec "${f}")" != 'h264' ]]
-	then
-		echo "'${f}' is not encoded with AVC (H.264). Skipping..."
-		continue
-	fi
+		## shellcheck nags about "get_video_codec "${f}""'s exit code
+		# shellcheck disable=SC2312
+		if [[ "$(get_video_codec "${f}")" != 'h264' ]]
+		then
+			echo "'${f}' is not encoded with AVC (H.264). Skipping..."
+			continue
+		fi
 
-	echo "Transcoding '${f}' to HEVC"
+		echo "Transcoding '${f}' to HEVC"
 
-	if ! transcode_to_hevc "${f}"
-	then
-		echo "Failed to convert '${f}' to HEVC"
-		exit 254
-	fi
+		if ! transcode_to_hevc "${f}"
+		then
+			echo "Failed to convert '${f}' to HEVC"
+			exit 254
+		fi
+	done
 done
 shopt -u globstar
+shopt -u nullglob
