zsh/funcs: add update-git-repos function
`update-git-repos` loops over git repo paths in
`${HOME}/.local/config/git-repos` file, and runs
`git remote update -p && git pull` on them.

`git-repos` file contains one git repo path per line. A line is a
sequence of zero or more non-newline characters plus a terminating
newline character.

See https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206
for POSIX's definition of line.

diff --git a/config/zsh/funcs b/config/zsh/funcs
--- a/config/zsh/funcs
+++ b/config/zsh/funcs
@@ -398,5 +398,60 @@ function telnet_log {
 	"${__telnet}" "$@" | "${__tee}" -i telnet_"$("${__date}" +%F_%T)".log
 }
 
+function update-git-repos {
+	local repo_list_file
+	local repo_list
+	local git_dir
+	local repo
+
+	repo_list_file="${HOME}/.local/config/git-repos"
+
+	if ! [ -f "${repo_list_file}" ]; then
+		mkdir -p "$(dirname "${repo_list_file}")"
+		touch "${repo_list_file}"
+		echo "Created empty config file at ${repo_list_file}."
+		echo "Add git repo paths to it, one path per line"
+		return 1
+	fi
+
+	repo_list="$(< "${repo_list_file}")"
+	if [ -z "${repo_list}" ]; then
+		echo "Repo list is empty. Please update ${repo_list_file}"
+		echo "${repo_list_file} should contain one git repo path per line"
+		return 255
+	fi
+
+	# loop over repo list, and run `git remote update -p && git pull` on them.
+	# "(f)" in "${(f)repo_list}" used to convert string into array, split
+	# from newline characters
+	for repo_path in "${(f)repo_list}"; do
+		repo="$(basename "${repo_path}")"
+
+		echo "Processing ${repo} @ ${repo_path}"
+
+		git_dir="$(git -C "${repo_path}" rev-parse --git-dir 2>/dev/null)"
+		if [ -z "${git_dir}" ]; then
+			echo "Could not determine GIT_DIR for repo ${repo}. Skipping..."
+			continue
+		fi
+
+		# GIT_DIR might be an absolute path, unrelated to "${repo_path}"
+		if ! [ -d "${repo_path}/${git_dir}" ] && ! [ -d "${git_dir}" ]; then
+			echo "It looks like ${repo} is not a git repository. Skipping..."
+			continue
+		fi
+		echo "Fetching changes for ${repo}"
+		if ! git -C "${repo_path}" remote update -p; then
+			echo "git update failed for ${repo}"
+			return 254
+		fi
+		echo "Update working tree for ${repo}"
+		if ! git -C "${repo_path}" pull; then
+			echo "git pull failed for ${repo}"
+			return 253
+		fi
+	done
+}
+
 # shellcheck source=/dev/null disable=SC2154
 [ -f "${ZSH_CONFIG_LOCAL_HOME}/funcs" ] && source "${ZSH_CONFIG_LOCAL_HOME}/funcs"
