add heic_to_x and its helper functions
heic_to_x can be used to convert images in HEIF/HEIC format to regular
image formats.

This function depends on `magick` command from `imagemagick`

diff --git a/config/zsh/funcs b/config/zsh/funcs
--- a/config/zsh/funcs
+++ b/config/zsh/funcs
@@ -9,6 +9,21 @@ function find_exec_in_path {
 	which -a "$1" | grep -e "^/" | head -1
 }
 
+# check if given argument is numeric or not
+function is_numeric {
+	case "${1#[+-]}" in
+		(*[!0123456789]*)
+			return 1
+			;;
+		('')
+			return 1
+			;;
+		(*)
+			return 0
+			;;
+	esac
+}
+
 # wrapper for ed(1) to change ed's prompt.
 function ed {
 	local __exec
@@ -460,6 +475,118 @@ HELP
 		fi
 	done
 }
+
+# heic_to_x - convert given heic image (hevc encoding) to desired format
+#
+# This functions depends on `magick` command from imagemagick
+# see `heic_to_x -h` for usage
+function heic_to_x {
+	local _ans
+	local format
+	local input
+	local monitor
+	local output
+	local quality
+
+	_ans=''
+	format=''
+	input=''
+	monitor='false'
+	output=''
+	quality='100'
+
+	if [ -z "$(command -v magick)" ]; then
+		echo 'magick (imagemagick) not found in PATH'
+		return 255
+	fi
+
+	while getopts ':f:h:i:mo:q:' opt; do
+		case "${opt}" in
+			f)
+				format="${OPTARG}"
+				;;
+			i)
+				input="${OPTARG}"
+				;;
+			m)
+				monitor='true'
+				;;
+			q)
+				quality="${OPTARG}"
+				;;
+			h)
+				;&
+			*)
+				cat <<- 'HELP'
+heic_to_x -f format -i file [-q quality]
+options:
+    -f format: format/extension for output file
+    -i file: input file in `heic` format
+    -h: show this help
+    -m: show perogress bar of operation
+    -q quality: quality level of output, in percentage (default 100)
+HELP
+				return 1
+				;;
+		esac
+	done
+	shift $((OPTIND-1))
+
+	if [ -z "${input}" ]; then
+		echo "Missing input file"
+		return 254
+	fi
+
+	if [ -z "${format}" ]; then
+		echo "Missing output format"
+		return 253
+	fi
+
+	if ! is_numeric "${quality}"; then
+		echo "Quality value is not numeric"
+		return 252
+	fi
+
+	if [ "${quality}" -gt '100' ] || [ "${quality}" -lt '0' ]; then
+		echo "Quality is not between [0-100]"
+		return 251
+	fi
+
+	output="${input%.*}.${format}"
+
+	# because `magick` does not check if output file is already exists
+	if [ -e "${output}" ]; then
+		echo "File ${output} already exists, overwrite?"
+		select _ans in 'Yes' 'No'; do
+			case "${_ans}" in
+				Yes)
+					break
+					;;
+				No)
+					return 2
+					;;
+			esac
+		done
+	fi
+
+	if [ 'true' = "${monitor}" ]; then
+		magick '-monitor' "${input}" '-quality' "${quality}" "${output}"
+	else
+		magick "${input}" '-quality' "${quality}" "${output}"
+	fi
+}
+
+## extra helpers for using heic_to_x
+# heic_to_jpg - convert heic iamges to jpg
+function heic_to_jpg {
+	heic_to_x -f 'jpg' "${@}"
+}
+
+# heic_to_png - convert heic images to png
+function heic_to_png {
+	heic_to_x -f 'png' "${@}"
+}
+## end of extra helpers for heic_to_x
 
 #
 # lsifr - list installed packages from given pacman repo
